services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - MONGO_URI=mongodb://localhost:27017/wallet-system
      - REDIS_URI=redis://redis:6379
      - NODE_ENV=development
      - CORS_ALLOWED_ORIGIN=http://localhost:5173
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"