services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - MONGO_URI=mongodb+srv://albinpariyarathu:qMWQHsrFF7bvwxNd@cluster0.ajmjpkj.mongodb.net/wallet-system?retryWrites=true&w=majority&appName=Cluster0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - CORS_ALLOWED_ORIGIN=http://localhost:5173
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"


      